name: Sync Github Commit to Notion
description: Sync your commits to Notion
branding:
  icon: refresh-cw
  color: white
inputs:
  notion_secret:
    description: Notion secret is required
    required: true
  notion_database:
    description: Notion database ID is required
    required: true
  branch:
    description: Branch name
    required: true
  commit_description:
    description: Description
    required: true
    default: Description
  commit_by:
    description: Commit By
    required: true
    default: Commit By
  commit_branch:
    description: Branch header
    required: true
    default: Branch
  project:
    description: Project
    required: true
    default: Project
  commit_id:
    description: Commit ID
    required: true
    default: Commit ID
runs:
  using: node16
  main: index.js
